// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SchoolAut0mater.CoreService.MITs;
using SchoolAut0mater.CoreService.MITs.Item;
using SchoolAut0mater.CoreService.Shared;
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Content;

// ReSharper disable once CheckNamespace
namespace SchoolAut0mater.CoreService.MITs;

public interface IMITItemsAppService : IApplicationService
{
    Task<PagedResultDto<MITItemWithNavigationPropertiesDto>> GetListAsync(GetMITItemsInput input);

    Task<MITItemWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(int id);

    Task<MITItemDto> GetAsync(int id);

    Task<PagedResultDto<LookupDto<Int32>>> GetMITCatalogLookupAsync(LookupRequestDto input);

    Task DeleteAsync(int id);

    Task<MITItemDto> CreateAsync(MITItemCreateDto input);

    Task<MITItemDto> UpdateAsync(int id, MITItemUpdateDto input);

    Task<IRemoteStreamContent> GetListAsExcelFileAsync(MITItemExcelDownloadDto input);

    Task<DownloadTokenResultDto> GetDownloadTokenAsync();
}
