// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SchoolAut0mater.CoreService.MITs.Catalog;
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SchoolAut0mater.CoreService.MITs;

public interface IMITCatalogsAppService : IApplicationService
{
    Task<PagedResultDto<MITCatalogDto>> GetListAsync(GetMITCatalogsInput input);

    Task<MITCatalogDto> GetAsync(int id);

    Task<MITCatalogDto> GetAsync(string code);
}
