// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SchoolAut0mater.CoreService.MITs;
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace SchoolAut0mater.CoreService.MITs;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMITCatalogsAppService), typeof(MITCatalogClientProxy))]
public partial class MITCatalogClientProxy : ClientProxyBase<IMITCatalogsAppService>, IMITCatalogsAppService
{
    public virtual async Task<PagedResultDto<MITCatalogDto>> GetListAsync(GetMITCatalogsInput input)
    {
        return await RequestAsync<PagedResultDto<MITCatalogDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetMITCatalogsInput), input }
        });
    }

    public virtual async Task<MITCatalogDto> GetAsync(int id)
    {
        return await RequestAsync<MITCatalogDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(int), id }
        });
    }

    public virtual async Task<MITCatalogDto> GetAsync(string code)
    {
        return await RequestAsync<MITCatalogDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), code }
        });
    }
}
