// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using SchoolAut0mater.CoreService.MITs;
using SchoolAut0mater.CoreService.MITs.Catalog;
using SchoolAut0mater.CoreService.MITs.Item;

// ReSharper disable once CheckNamespace
namespace SchoolAut0mater.CoreService.MITs;

public class MITItemWithNavigationPropertiesDto
{
    public MITItemDto MITItem { get; set; }

    public MITCatalogDto MITCatalog { get; set; }
}
