config:
  selfUrl: https://schoolaut0mater-st-saas
  corsOrigins: https://schoolaut0mater-st-gateway-web,https://schoolaut0mater-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://schoolaut0mater-st-authserver
    requireHttpsMetadata: # "false"
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: schoolaut0mater-st-saas
  tlsSecret: schoolaut0mater-tls

image:
  repository: mycompanyname/schoolaut0mater-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      