config:
  selfUrl: # 
  gatewayUrl: # 
  authServer:
      authority: # http://schoolaut0mater-st-authserver
      requireHttpsMetadata: # false
      responseType: "code"
      strictDiscoveryDocumentValidation: false
      skipIssuerCheck: true

ingress:
  host: # schoolaut0mater-st-angular
  tlsSecret: schoolaut0mater-tls

image:
  repository: mycompanyname/schoolaut0mater-app-angular
  tag: latest
  pullPolicy: IfNotPresent

env: {}