// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SchoolAut0mater.CoreService.Samples;
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SchoolAut0mater.CoreService.Samples;

public interface ISampleAppService : IApplicationService
{
    Task<SampleDto> GetAsync();

    Task<SampleDto> GetAuthorizedAsync();
}
