// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using SchoolAut0mater.CoreService.Samples;
using System;

// ReSharper disable once CheckNamespace
namespace SchoolAut0mater.CoreService.Samples;

public class SampleDto
{
    public int Value { get; set; }
}
